theme:          iiifc-theme
source:         source
permalink:      pretty

url:            'https://preview.iiif.io/root/wireframe'
api_url:        'https://preview.iiif.io/api/wireframe/api'

plugins:
  - jekyll-data
  - jekyll-gzip
  - jekyll-redirect-from

notification:
  enabled: true
  title: This website design is in pre-beta.
  subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  link: '#'
  link_label: This is a test link
