theme:          iiifc-theme
source:         source
permalink:      pretty

root_url:       ''
api_url:        https://preview.iiif.io/api/wireframe/api
cookbook_url:  https://preview.iiif.io/cookbook/wireframe


plugins:
  - jekyll-data
  - jekyll-gzip
  - jekyll-redirect-from
  - jekyll-liquify

notification:
  enabled: true
  title: This website design is in pre-beta.
  subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  link: '#'
  link_label: This is a test link
