url:            ''
baseurl:        ''
permalink:      pretty
title:          "IIIF | International Image Interoperability Framework"
theme:          iiifc-theme
source:         source

sass:
  style:        compressed
  sass_dir:     _sass
exclude:        [node_modules]
collections:
  pages:
    output: true

organization:
  acronym:      IIIF
  title:        International Image Interoperability Framework
  tagline:      "International Image Interoperability Framework: A community driven image framework with well defined APIs for making the world’s image repositories interoperable and accessible"
  email:        iiif-discuss@googlegroups.com
  url:          //iiif.io
  logo:         assets/images/logo-sm.png

navbar_menu:
  - label: 'Home'
    link: '/'
  - label: 'Demos'
    link: '/demos'
  - label: 'News & Events'
    link: '/news-and-events'
  - label: 'Get Involved'
    link: '/get-involved'
    sub:
      - label: 'Community Groups'
        link: ''
      - label: 'Consortium'
        link: ''
      - label: 'Join Newsletter'
        link: ''
      - label: 'Contact Us'
        link: ''
  - label: 'Get Started'
    link: '/get-started'
    sub:
      - label: 'How It Works'
        link: ''
      - label: 'APIs & Documentation'
        link: ''
      - label: 'Cookbooks'
        link: ''
      - label: 'Training'
        link: ''

image_api:
  latest:
    major: 3
    minor: 0
    patch: 0
presentation_api:
  latest:
    major: 3
    minor: 0
    patch: 0
shared_canvas:
  latest:
    major: 1
    minor: 0
    patch: 0
search_api:
  latest:
    major: 1
    minor: 0
    patch: 0
auth_api:
  latest:
    major: 1
    minor: 0
    patch: 0
